server {
    listen 80;
    server_name _; # Catch-all server name

    # Root directory containing the static build files
    root /usr/share/nginx/html;
    # Default file to serve
    index index.html;

    # Serve static files directly
    location / {
        try_files $uri $uri/ /index.html;
    }
}
