name: Build and Package for macOS

on:
  push:
    tags:
      - '*'
    branches:
      - 'macos-executable'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew update
          brew install sdl2 sdl2_image sdl2_mixer

      - name: Build project
        run: |
          export SDL2_INCLUDE_DIR="/opt/homebrew/include/SDL2"
          export SDL2_LIB_DIR="/opt/homebrew/lib"
          make -f Makefile.release.macos
          ls -l

      - name: Run smoke test
        run: ./Sartre --smoke
