name: Build and Package for macOS

on:
  push:
    tags:
      - '*'
    branches:
      - 'macos-executable'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew update
          brew install sdl2

      - name: Build SDL2_image to avoid a lot of dylibs
        run: |
          git clone https://github.com/libsdl-org/SDL_image.git
          cd SDL_image
          git checkout release-2.8.2
          mkdir build
          cd build
          mkdir -p ../../local
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=../../local \
            -DSDL2IMAGE_AVIF=OFF \
            -DSDL2IMAGE_BMP=OFF \
            -DSDL2IMAGE_GIF=OFF \
            -DSDL2IMAGE_JPG=OFF \
            -DSDL2IMAGE_JXL=OFF \
            -DSDL2IMAGE_LBM=OFF \
            -DSDL2IMAGE_PCX=OFF \
            -DSDL2IMAGE_PNG=ON \
            -DSDL2IMAGE_PNM=OFF \
            -DSDL2IMAGE_QOI=OFF \
            -DSDL2IMAGE_SVG=OFF \
            -DSDL2IMAGE_TGA=OFF \
            -DSDL2IMAGE_TIF=OFF \
            -DSDL2IMAGE_WEBP=OFF \
            -DSDL2IMAGE_XCF=OFF \
            -DSDL2IMAGE_XPM=OFF \
            -DSDL2IMAGE_XV=OFF
          make
          make install

      - name: Build SDL2_mixer to avoid a lot of dylibs
        run: |
          git clone https://github.com/libsdl-org/SDL_mixer.git
          cd SDL_mixer
          git checkout release-2.8.0
          mkdir build
          cd build
          mkdir -p ../../local
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=../../local \
            -DSDL2MIXER_CMD=OFF \
            -DSDL2MIXER_FLAC=OFF \
            -DSDL2MIXER_GME=OFF \
            -DSDL2MIXER_MOD=OFF \
            -DSDL2MIXER_MIDI=OFF \
            -DSDL2MIXER_OPUS=OFF \
            -DSDL2MIXER_VORBIS=OFF \
            -DSDL2MIXER_WAVE=OFF \
            -DSDL2MIXER_WAVPACK=OFF \
            -DSDL2MIXER_MP3=ON
          make
          make install

      - name: Build project
        run: |
          export SDL2_INCLUDE_DIR="/opt/homebrew/include/SDL2"
          export SDL2_LIB_DIR="/opt/homebrew/lib"
          export SDL2_LOCAL_INCLUDE_DIR="./local/include/SDL2"
          export SDL2_LOCAL_LIB_DIR="./local/lib"
          ls -l ./
          ls -l ./local
          make -f Makefile.release.macos

      - name: Run smoke test
        run: ./Sartre --smoke
